name: Daily Commit

on:
  schedule:
    - cron: "0 1 * * *" # setiap hari
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update file
        run: |
          echo "Update $(date)" >> log.txt

      - name: Commit & Push
        run: |
          git config --global user.name "Nyxveil-D"
          git config --global user.email "kiranime155@gmail.com"
          git add .
          git commit -m "daily commit" || echo "no changes"
          git push
